#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['docutils',
 'docutils.languages',
 'docutils.parsers',
 'docutils.parsers.rst',
 'docutils.parsers.rst.directives',
 'docutils.parsers.rst.languages',
 'docutils.readers',
 'docutils.transforms',
 'docutils.utils',
 'docutils.utils.math',
 'docutils.writers',
 'docutils.writers.html4css1',
 'docutils.writers.html5_polyglot',
 'docutils.writers.latex2e',
 'docutils.writers.odf_odt',
 'docutils.writers.pep_html',
 'docutils.writers.s5_html',
 'docutils.writers.xetex']

package_data = \
{'': ['*'],
 'docutils.parsers.rst': ['include/*'],
 'docutils.writers.s5_html': ['themes/*',
                              'themes/big-black/*',
                              'themes/big-white/*',
                              'themes/default/*',
                              'themes/medium-black/*',
                              'themes/medium-white/*',
                              'themes/small-black/*',
                              'themes/small-white/*']}

entry_points = \
{'console_scripts': ['docutils = docutils.__main__:main',
                     'rst2html = docutils.core:rst2html',
                     'rst2html4 = docutils.core:rst2html4',
                     'rst2html5 = docutils.core:rst2html5',
                     'rst2latex = docutils.core:rst2latex',
                     'rst2man = docutils.core:rst2man',
                     'rst2odt = docutils.core:rst2odt',
                     'rst2pseudoxml = docutils.core:rst2pseudoxml',
                     'rst2s5 = docutils.core:rst2s5',
                     'rst2xetex = docutils.core:rst2xetex',
                     'rst2xml = docutils.core:rst2xml']}

setup(name='docutils',
      version='0.21.2',
      description='Docutils -- Python Documentation Utilities',
      author=None,
      author_email='David Goodger <goodger@python.org>',
      url=None,
      packages=packages,
      package_data=package_data,
      entry_points=entry_points,
      python_requires='>=3.9',
     )
